version: "3.9"
services:
      
  wordpress_visionarytalentkids:
    container_name: wordpress_visionarytalentkids
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_visionarytalentkids-db
      - WORDPRESS_DB_NAME=wordpress_visionarytalentkids
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_visionarytalentkids:/var/www/wordpress_visionarytalentkids
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_visionarytalentkids-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_visionarytalentkids-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_visionarytalentkids.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_visionarytalentkids-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_visionarytalentkids-insecure.entrypoints: web
        traefik.http.routers.wordpress_visionarytalentkids-insecure.service: wordpress_visionarytalentkids
        traefik.http.routers.wordpress_visionarytalentkids-insecure.middlewares: wordpress_visionarytalentkids-redirect
        # Websecure
        traefik.http.routers.wordpress_visionarytalentkids.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_visionarytalentkids.entrypoints: websecure
        traefik.http.routers.wordpress_visionarytalentkids.service: wordpress_visionarytalentkids
        traefik.http.routers.wordpress_visionarytalentkids.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_visionarytalentkids-local-insecure.rule: Host(`wordpress_visionarytalentkids.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_visionarytalentkids-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_visionarytalentkids-local-insecure.service: wordpress_visionarytalentkids
        traefik.http.routers.wordpress_visionarytalentkids-local-insecure.middlewares: wordpress_visionarytalentkids-redirect
        # Local domain secure
        traefik.http.routers.wordpress_visionarytalentkids-local.rule: Host(`wordpress_visionarytalentkids.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_visionarytalentkids-local.entrypoints: websecure
        traefik.http.routers.wordpress_visionarytalentkids-local.service: wordpress_visionarytalentkids
        traefik.http.routers.wordpress_visionarytalentkids-local.tls: true
        runtipi.managed: true
  wordpress_visionarytalentkids-db:
    container_name: wordpress_visionarytalentkids-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_visionarytalentkids
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpressvisionarytalentkids:/var/lib/visionarytalentkids
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
