version: '3.9'

services:
  grampsweb:
    image: ghcr.io/gramps-project/grampsweb:v24.12.2
    container_name: grampsweb
    restart: unless-stopped
    networks:
      - tipi_main_network
    environment:
      GRAMPSWEB_TREE: ${GRAMPSWEB_TREE}
      GUNICORN_CMD_ARGS: "--timeout 3600 --workers 8 --worker-class gthread --threads 4 --limit-request-field_size 32760 --limit-request-line 32760"
      GRAMPSWEB_LLM_BASE_URL: "http://192.168.1.224:11435"
      GRAMPSWEB_LLM_MODEL: "phi4"
      GRAMPSWEB_LLM_EMBEDDING_MODEL: "nomic-embed-text"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_GRAMPS} 
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ${APP_DATA_DIR}/users:/app/users
      - ${APP_DATA_DIR}/index:/app/indexdir
      - ${APP_DATA_DIR}/thumb_cache:/app/thumbnail_cache
      - ${APP_DATA_DIR}/cache:/app/cache
      - ${APP_DATA_DIR}/secret:/app/secret
      - ${APP_DATA_DIR}/db:/root/.gramps/grampsdb
      - /srdata/runtipi/runtipi/media/data/familytree:/app/media
      - ${APP_DATA_DIR}/tmp:/tmp
    labels:
       # Main
      runtipi.managed: true
      traefik.enable: true
      traefik.http.middlewares.grampsweb-web-redirect.redirectscheme.scheme: https
      traefik.http.services.grampsweb.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.grampsweb-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grampsweb-insecure.entrypoints: web
      traefik.http.routers.grampsweb-insecure.service: grampsweb
      traefik.http.routers.grampsweb-insecure.middlewares: grampsweb-web-redirect
      # Websecure
      traefik.http.routers.grampsweb.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grampsweb.entrypoints: websecure
      traefik.http.routers.grampsweb.service: grampsweb
      traefik.http.routers.grampsweb.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.grampsweb-local-insecure.rule: Host(`grampsweb.${LOCAL_DOMAIN}`)
      traefik.http.routers.grampsweb-local-insecure.entrypoints: web
      traefik.http.routers.grampsweb-local-insecure.service: grampsweb
      traefik.http.routers.grampsweb-local-insecure.middlewares: grampsweb-web-redirect
      # Local domain secure
      traefik.http.routers.grampsweb-local.rule: Host(`grampsweb.${LOCAL_DOMAIN}`)
      traefik.http.routers.grampsweb-local.entrypoints: websecure
      traefik.http.routers.grampsweb-local.service: grampsweb
      traefik.http.routers.grampsweb-local.tls: true

  postgres_gramps:
    image: ghcr.io/davidmstraub/gramps-postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ADMIN}
      POSTGRES_PASSWORD_GRAMPS: ${POSTGRES_PASSWORD_GRAMPS}
      POSTGRES_PASSWORD_GRAMPS_USER: ${POSTGRES_PASSWORD_GRAMPS_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tipi_main_network

networks:
  tipi_main_network:
    name: runtipi_tipi_main_network
    external: true

volumes:
  postgres_data:

