version: "3.9"
services:
      
  wordpress_corbieplays:
    container_name: wordpress_corbieplays
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_corbieplays-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_corbieplays-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_corbieplays-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_corbieplays.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_corbieplays-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_corbieplays-insecure.entrypoints: web
        traefik.http.routers.wordpress_corbieplays-insecure.service: wordpress_corbieplays
        traefik.http.routers.wordpress_corbieplays-insecure.middlewares: wordpress_corbieplays-redirect
        # Websecure
        traefik.http.routers.wordpress_corbieplays.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_corbieplays.entrypoints: websecure
        traefik.http.routers.wordpress_corbieplays.service: wordpress_corbieplays
        traefik.http.routers.wordpress_corbieplays.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_corbieplays-local-insecure.rule: Host(`wordpress_corbieplays.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_corbieplays-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_corbieplays-local-insecure.service: wordpress_corbieplays
        traefik.http.routers.wordpress_corbieplays-local-insecure.middlewares: wordpress_corbieplays-redirect
        # Local domain secure
        traefik.http.routers.wordpress_corbieplays-local.rule: Host(`wordpress_corbieplays.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_corbieplays-local.entrypoints: websecure
        traefik.http.routers.wordpress_corbieplays-local.service: wordpress_corbieplays
        traefik.http.routers.wordpress_corbieplays-local.tls: true
        runtipi.managed: true
  wordpress_corbieplays-db:
    container_name: wordpress_corbieplays-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
