version: "3.9"
services:
      
  wordpress_lickingvape:
    container_name: wordpress_lickingvape
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_lickingvape-db
      - WORDPRESS_DB_NAME=wordpress_lickingvape
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_lickingvape:/var/www/wordpress_lickingvape
      - ./uploads.ini:/user-config/uploads.ini 
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_lickingvape-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_lickingvape-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_lickingvape.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_lickingvape-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_lickingvape-insecure.entrypoints: web
        traefik.http.routers.wordpress_lickingvape-insecure.service: wordpress_lickingvape
        traefik.http.routers.wordpress_lickingvape-insecure.middlewares: wordpress_lickingvape-redirect
        # Websecure
        traefik.http.routers.wordpress_lickingvape.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_lickingvape.entrypoints: websecure
        traefik.http.routers.wordpress_lickingvape.service: wordpress_lickingvape
        traefik.http.routers.wordpress_lickingvape.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_lickingvape-local-insecure.rule: Host(`wordpress_lickingvape.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_lickingvape-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_lickingvape-local-insecure.service: wordpress_lickingvape
        traefik.http.routers.wordpress_lickingvape-local-insecure.middlewares: wordpress_lickingvape-redirect
        # Local domain secure
        traefik.http.routers.wordpress_lickingvape-local.rule: Host(`wordpress_lickingvape.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_lickingvape-local.entrypoints: websecure
        traefik.http.routers.wordpress_lickingvape-local.service: wordpress_lickingvape
        traefik.http.routers.wordpress_lickingvape-local.tls: true
        runtipi.managed: true
  wordpress_lickingvape-db:
    container_name: wordpress_lickingvape-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_lickingvape
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_lickingvape:/var/lib/wordpress_lickingvape
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
