version: "3.9"
services:

  wordpress-mneumonicme:
    container_name: wordpress-mneumonicme
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress-mneumonicme-db
      - WORDPRESS_DB_NAME=wordpress-mneumonicme-db
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress-mneumonicme-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-mneumonicme-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-mneumonicme.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-mneumonicme-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-mneumonicme-insecure.entrypoints: web
        traefik.http.routers.wordpress-mneumonicme-insecure.service: wordpress-mneumonicme
        traefik.http.routers.wordpress-mneumonicme-insecure.middlewares: wordpress-mneumonicme-redirect
        # Websecure
        traefik.http.routers.wordpress-mneumonicme.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-mneumonicme.entrypoints: websecure
        traefik.http.routers.wordpress-mneumonicme.service: wordpress-mneumonicme
        traefik.http.routers.wordpress-mneumonicme.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-mneumonicme-local-insecure.rule: Host(`wordpress-mneumonicme.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-mneumonicme-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-mneumonicme-local-insecure.service: wordpress-mneumonicme
        traefik.http.routers.wordpress-mneumonicme-local-insecure.middlewares: wordpress-mneumonicme-redirect
        # Local domain secure
        traefik.http.routers.wordpress-mneumonicme-local.rule: Host(`wordpress-mneumonicme.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-mneumonicme-local.entrypoints: websecure
        traefik.http.routers.wordpress-mneumonicme-local.service: wordpress-mneumonicme
        traefik.http.routers.wordpress-mneumonicme-local.tls: true
        runtipi.managed: true
  wordpress-mneumonicme-db:
    container_name: wordpress-mneumonicme-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress-mneumonicme-db
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

