version: "3.9"
services:
      
  wordpress:
    container_name: wordpress_stepparentpath
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_stepparentpath-db
      - WORDPRESS_DB_NAME=wordpress_stepparentpath
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_stepparentpath:/var/www/stepparentpath
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_stepparentpath-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_stepparentpath-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_stepparentpath.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_stepparentpath-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_stepparentpath-insecure.entrypoints: web
        traefik.http.routers.wordpress_stepparentpath-insecure.service: wordpress
        traefik.http.routers.wordpress_stepparentpath-insecure.middlewares: wordpress-redirect
        # Websecure
        traefik.http.routers.wordpress_stepparentpath.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_stepparentpath.entrypoints: websecure
        traefik.http.routers.wordpress_stepparentpath.service: wordpress_stepparentpath
        traefik.http.routers.wordpress_stepparentpath.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_stepparentpath-local-insecure.rule: Host(`wordpress_stepparentpath.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_stepparentpath-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_stepparentpath-local-insecure.service: wordpress_stepparentpath
        traefik.http.routers.wordpress_stepparentpath-local-insecure.middlewares: wordpress_stepparentpath-redirect
        # Local domain secure
        traefik.http.routers.wordpress_stepparentpath-local.rule: Host(`wordpress_stepparentpath.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_stepparentpath-local.entrypoints: websecure
        traefik.http.routers.wordpress_stepparentpath-local.service: wordpress_stepparentpath
        traefik.http.routers.wordpress_stepparentpath-local.tls: true
        runtipi.managed: true
  wordpress_stepparentpath-db:
    container_name: wordpress_stepparentpath-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_stepparentpath
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/stepparentpath:/var/lib/stepparentpath
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
