version: "3.9"
services:
      
  wordpress_desirearts:
    container_name: wordpress_desirearts
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_desirearts-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_desirearts-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-desirearts-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-desirearts.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-desirearts-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-desirearts-insecure.entrypoints: web
        traefik.http.routers.wordpress-desirearts-insecure.service: wordpress-desirearts
        traefik.http.routers.wordpress-desirearts-insecure.middlewares: wordpress-desirearts-redirect
        # Websecure
        traefik.http.routers.wordpress-desirearts.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-desirearts.entrypoints: websecure
        traefik.http.routers.wordpress-desirearts.service: wordpress-desirearts
        traefik.http.routers.wordpress-desirearts.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-desirearts-local-insecure.rule: Host(`wordpress-desirearts.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-desirearts-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-desirearts-local-insecure.service: wordpress-desirearts
        traefik.http.routers.wordpress-desirearts-local-insecure.middlewares: wordpress-desirearts-redirect
        # Local domain secure
        traefik.http.routers.wordpress-desirearts-local.rule: Host(`wordpress-desirearts.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-desirearts-local.entrypoints: websecure
        traefik.http.routers.wordpress-desirearts-local.service: wordpress-desirearts
        traefik.http.routers.wordpress-desirearts-local.tls: true
        runtipi.managed: true
  wordpress_desirearts-db:
    container_name: wordpress_desirearts-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
