version: "3.9"
services:
      
  wordpress_desirearts:
    container_name: wordpress_desirearts
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_desirearts-db
      - WORDPRESS_DB_NAME=wordpress_desirearts
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_desirearts:/var/www/desirearts
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_desirearts-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_desirearts-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_desirearts.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_desirearts-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_desirearts-insecure.entrypoints: web
        traefik.http.routers.wordpress_desirearts-insecure.service: wordpress_desirearts
        traefik.http.routers.wordpress_desirearts-insecure.middlewares: wordpress_desirearts-redirect
        # Websecure
        traefik.http.routers.wordpress_desirearts.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_desirearts.entrypoints: websecure
        traefik.http.routers.wordpress_desirearts.service: wordpress_desirearts
        traefik.http.routers.wordpress_desirearts.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_desirearts-local-insecure.rule: Host(`wordpress_desirearts.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_desirearts-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_desirearts-local-insecure.service: wordpress_desirearts
        traefik.http.routers.wordpress_desirearts-local-insecure.middlewares: wordpress_desirearts-redirect
        # Local domain secure
        traefik.http.routers.wordpress_desirearts-local.rule: Host(`wordpress_desirearts.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_desirearts-local.entrypoints: websecure
        traefik.http.routers.wordpress_desirearts-local.service: wordpress_desirearts
        traefik.http.routers.wordpress_desirearts-local.tls: true
        runtipi.managed: true
  wordpress_desirearts-db:
    container_name: wordpress_desirearts-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_desirearts
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_desirearts:/var/lib/wordpress_desirearts
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
