/*
  Generated by openapi-typescript.
  Run: pnpm gen:client
*/
export type paths = {
  "/health": {
    get: {
      responses: {
        200: { content: { "application/json": { status: string } } };
      };
    };
  };
  "/auth/register": {
    post: {
      responses: {
        200: { content: { "application/json": { id: number; email: string; created_at: string } } };
      };
    };
  };
  "/auth/login": {
    post: {
      responses: {
        200: { content: { "application/json": { access_token: string; token_type: string } } };
      };
    };
  };
  "/me": {
    get: {
      responses: {
        200: { content: { "application/json": { id: number; email: string; created_at: string } } };
      };
    };
  };
  "/runs": {
    get: {
      responses: {
        200: { content: { "application/json": Array<Record<string, unknown>> } } };
      };
    };
    post: {
      responses: {
        200: { content: { "application/json": Record<string, unknown> } } };
      };
    };
  };
  "/ai/quest": {
    post: {
      responses: {
        200: { content: { "application/json": { quest_text: string; metadata: Record<string, unknown> } } };
      };
    };
  };
  "/ai/narrate": {
    post: {
      responses: {
        200: { content: { "application/json": { narration_text: string } } };
      };
    };
  };
  "/exports/run/{run_id}": {
    post: {
      responses: {
        200: { content: { "application/json": { status: string; object_key: string } } };
      };
    };
  };
};
