version: "3.9"
services:

  wordpress-jogmania:
    container_name: wordpress-jogmania
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress-jogmania-db
      - WORDPRESS_DB_NAME=wordpress-jogmania-db
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress-jogmania-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-jogmania-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-jogmania.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-jogmania-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-jogmania-insecure.entrypoints: web
        traefik.http.routers.wordpress-jogmania-insecure.service: wordpress-jogmania
        traefik.http.routers.wordpress-jogmania-insecure.middlewares: wordpress-jogmania-redirect
        # Websecure
        traefik.http.routers.wordpress-jogmania.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-jogmania.entrypoints: websecure
        traefik.http.routers.wordpress-jogmania.service: wordpress-jogmania
        traefik.http.routers.wordpress-jogmania.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-jogmania-local-insecure.rule: Host(`wordpress-jogmania.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-jogmania-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-jogmania-local-insecure.service: wordpress-jogmania
        traefik.http.routers.wordpress-jogmania-local-insecure.middlewares: wordpress-jogmania-redirect
        # Local domain secure
        traefik.http.routers.wordpress-jogmania-local.rule: Host(`wordpress-jogmania.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-jogmania-local.entrypoints: websecure
        traefik.http.routers.wordpress-jogmania-local.service: wordpress-jogmania
        traefik.http.routers.wordpress-jogmania-local.tls: true
        runtipi.managed: true
  wordpress-jogmania-db:
    container_name: wordpress-jogmania-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress-jogmania-db
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

