version: "3.9"
services:
      
  wordpress_elderseth:
    container_name: wordpress_elderseth
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_elderseth-db
      - WORDPRESS_DB_NAME=wordpress_elderseth
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_elderseth:/var/www/wordrpess_elderseth
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_elderseth-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_elderseth-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_elderseth.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_elderseth-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_elderseth-insecure.entrypoints: web
        traefik.http.routers.wordpress_elderseth-insecure.service: wordpress_elderseth
        traefik.http.routers.wordpress_elderseth-insecure.middlewares: wordpress_elderseth-redirect
        # Websecure
        traefik.http.routers.wordpress_elderseth.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_elderseth.entrypoints: websecure
        traefik.http.routers.wordpress_elderseth.service: wordpress_elderseth
        traefik.http.routers.wordpress_elderseth.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_elderseth-local-insecure.rule: Host(`wordpress_elderseth.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_elderseth-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_elderseth-local-insecure.service: wordpress_elderseth
        traefik.http.routers.wordpress_elderseth-local-insecure.middlewares: wordpress_elderseth-redirect
        # Local domain secure
        traefik.http.routers.wordpress_elderseth-local.rule: Host(`wordpress_elderseth.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_elderseth-local.entrypoints: websecure
        traefik.http.routers.wordpress_elderseth-local.service: wordpress_elderseth
        traefik.http.routers.wordpress_elderseth-local.tls: true
        runtipi.managed: true
  wordpress_elderseth-db:
    container_name: wordpress_elderseth-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_elderseth
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_elderseth-db:/var/lib/wordpress_elderseth-db
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
