version: "3.9"
services:
      
  wordpress_yoginilist:
    container_name: wordpress_yoginilist
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_yoginilist-db
      - WORDPRESS_DB_NAME=wordpress_yoginilist
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_yoginilist:/var/www/wordpress_yoginilist
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_yoginilist-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_yoginilist-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_yoginilist.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_yoginilist-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_yoginilist-insecure.entrypoints: web
        traefik.http.routers.wordpress_yoginilist-insecure.service: wordpress_yoginilist
        traefik.http.routers.wordpress_yoginilist-insecure.middlewares: wordpress_yoginilist-redirect
        # Websecure
        traefik.http.routers.wordpress_yoginilist.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_yoginilist.entrypoints: websecure
        traefik.http.routers.wordpress_yoginilist.service: wordpress_yoginilist
        traefik.http.routers.wordpress_yoginilist.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_yoginilist-local-insecure.rule: Host(`wordpress_yoginilist.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_yoginilist-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_yoginilist-local-insecure.service: wordpress_yoginilist
        traefik.http.routers.wordpress_yoginilist-local-insecure.middlewares: wordpress_yoginilist-redirect
        # Local domain secure
        traefik.http.routers.wordpress_yoginilist-local.rule: Host(`wordpress_yoginilist.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_yoginilist-local.entrypoints: websecure
        traefik.http.routers.wordpress_yoginilist-local.service: wordpress_yoginilist
        traefik.http.routers.wordpress_yoginilist-local.tls: true
        runtipi.managed: true
  wordpress_yoginilist-db:
    container_name: wordpress_yoginilist-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_yoginilist
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_yoginilist:/var/lib/wordpress_yoginilist
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
