version: "3.9"

services:
  ghost-ed:
    image: ghost:5.104.2
    container_name: ghost-ed
    depends_on:
      - ghost-eddb
    restart: unless-stopped
    ports:
      - ${APP_PORT}:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: ghost-eddb
      database__connection__user: tipi
      database__connection__password: ${GHOST_DATABASE_PASSWORD}
      database__connection__database: ghost-edtipi
      url: ${APP_PROTOCOL:-http}://${APP_DOMAIN}
      mail__transport: SMTP
      mail__options__service: ${GHOST_MAIL_SERVICE}
      mail__options__host: ${GHOST_MAIL_HOST}
      mail__options__port: ${GHOST_MAIL_PORT}
      mail__options__auth__user: ${GHOST_MAIL_USER}
      mail__options__auth__pass: ${GHOST_MAIL_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/content:/var/lib/ghost-ed/content
      - ${APP_DATA_DIR}/tmp:/tmp/
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.ghost-ed-web-redirect.redirectscheme.scheme: https
      traefik.http.services.ghost-ed.loadbalancer.server.port: 2368
      # Web
      traefik.http.routers.ghost-ed-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.ghost-ed-insecure.entrypoints: web
      traefik.http.routers.ghost-ed-insecure.service: ghost-ed
      traefik.http.routers.ghost-ed-insecure.middlewares: ghost-ed-web-redirect
      # Websecure
      traefik.http.routers.ghost-ed.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.ghost-ed.entrypoints: websecure
      traefik.http.routers.ghost-ed.service: ghost-ed
      traefik.http.routers.ghost-ed.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.ghost-ed-local-insecure.rule: Host(`ghost-ed.${LOCAL_DOMAIN}`)
      traefik.http.routers.ghost-ed-local-insecure.entrypoints: web
      traefik.http.routers.ghost-ed-local-insecure.service: ghost-ed
      traefik.http.routers.ghost-ed-local-insecure.middlewares: ghost-ed-web-redirect
      # Local domain secure
      traefik.http.routers.ghost-ed-local.rule: Host(`ghost-ed.${LOCAL_DOMAIN}`)
      traefik.http.routers.ghost-ed-local.entrypoints: websecure
      traefik.http.routers.ghost-ed-local.service: ghost-ed
      traefik.http.routers.ghost-ed-local.tls: true
      runtipi.managed: true
  ghost-eddb:
    container_name: ghost-eddb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DATABASE_PASSWORD}
      MYSQL_USER: tipi
      MYSQL_PASSWORD: ${GHOST_DATABASE_PASSWORD}
      MYSQL_DATABASE: ghost-edtipi
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
