version: "3.9"
services:
  nginx_data.rasies.com:
    image: nginx:1.25.3
    container_name: nginx_data
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data/config/nginx.conf:/etc/nginx/nginx.conf

    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.nginx_data-web-redirect.redirectscheme.scheme: https
      traefik.http.services.nginx_data.loadbalancer.server.port: 80
      # Web
      traefik.http.routers.nginx_data-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nginx_data-insecure.entrypoints: web
      traefik.http.routers.nginx_data-insecure.service: nginx_data
      traefik.http.routers.nginx_data-insecure.middlewares: nginx_data-web-redirect
      # Websecure
      traefik.http.routers.nginx_data.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nginx_data.entrypoints: websecure
      traefik.http.routers.nginx_data.service: nginx_data
      traefik.http.routers.nginx_data.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.nginx_data-local-insecure.rule: Host(`nginx_data.${LOCAL_DOMAIN}`)
      traefik.http.routers.nginx_data-local-insecure.entrypoints: web
      traefik.http.routers.nginx_data-local-insecure.service: nginx_data
      traefik.http.routers.nginx_data-local-insecure.middlewares: nginx_data-web-redirect
      # Local domain secure
      traefik.http.routers.nginx_data-local.rule: Host(`nginx_data.${LOCAL_DOMAIN}`)
      traefik.http.routers.nginx_data-local.entrypoints: websecure
      traefik.http.routers.nginx_data-local.service: nginx_data
      traefik.http.routers.nginx_data-local.tls: true
      runtipi.managed: true
