version: "3.9"
services:
      
  wordpress_blondesagainsttrump:
    container_name: wordpress_blondesagainsttrump
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_blondesagainsttrump-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_blondesagainsttrump-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_blondesagainsttrump-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_blondesagainsttrump.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_blondesagainsttrump-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_blondesagainsttrump-insecure.entrypoints: web
        traefik.http.routers.wordpress_blondesagainsttrump-insecure.service: wordpress_blondesagainsttrump
        traefik.http.routers.wordpress_blondesagainsttrump-insecure.middlewares: wordpress_blondesagainsttrump-redirect
        # Websecure
        traefik.http.routers.wordpress_blondesagainsttrump.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_blondesagainsttrump.entrypoints: websecure
        traefik.http.routers.wordpress_blondesagainsttrump.service: wordpress_blondesagainsttrump
        traefik.http.routers.wordpress_blondesagainsttrump.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_blondesagainsttrump-local-insecure.rule: Host(`wordpress_blondesagainsttrump.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_blondesagainsttrump-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_blondesagainsttrump-local-insecure.service: wordpress_blondesagainsttrump
        traefik.http.routers.wordpress_blondesagainsttrump-local-insecure.middlewares: wordpress_blondesagainsttrump-redirect
        # Local domain secure
        traefik.http.routers.wordpress_blondesagainsttrump-local.rule: Host(`wordpress_blondesagainsttrump.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_blondesagainsttrump-local.entrypoints: websecure
        traefik.http.routers.wordpress_blondesagainsttrump-local.service: wordpress_blondesagainsttrump
        traefik.http.routers.wordpress_blondesagainsttrump-local.tls: true
        runtipi.managed: true
  wordpress_blondesagainsttrump-db:
    container_name: wordpress_blondesagainsttrump-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
