version: "3.9"
services:
      
  wordpress_cuddleconfessions:
    container_name: wordpress_cuddleconfessions
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_cuddleconfessions-db
      - WORDPRESS_DB_NAME=
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_cuddleconfessions:/var/www/wordpress_cuddleconfessions
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_cuddleconfessions-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_cuddleconfessions-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_cuddleconfessions.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_cuddleconfessions-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_cuddleconfessions-insecure.entrypoints: web
        traefik.http.routers.wordpress_cuddleconfessions-insecure.service: wordpress_cuddleconfessions
        traefik.http.routers.wordpress_cuddleconfessions-insecure.middlewares: wordpress_cuddleconfessions-redirect
        # Websecure
        traefik.http.routers.wordpress_cuddleconfessions.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_cuddleconfessions.entrypoints: websecure
        traefik.http.routers.wordpress_cuddleconfessions.service: wordpress_cuddleconfessions
        traefik.http.routers.wordpress_cuddleconfessions.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_cuddleconfessions-local-insecure.rule: Host(`wordpress_cuddleconfessions.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_cuddleconfessions-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_cuddleconfessions-local-insecure.service: wordpress_cuddleconfessions
        traefik.http.routers.wordpress_cuddleconfessions-local-insecure.middlewares: wordpress_cuddleconfessions-redirect
        # Local domain secure
        traefik.http.routers.wordpress_cuddleconfessions-local.rule: Host(`wordpress_cuddleconfessions.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_cuddleconfessions-local.entrypoints: websecure
        traefik.http.routers.wordpress_cuddleconfessions-local.service: wordpress_cuddleconfessions
        traefik.http.routers.wordpress_cuddleconfessions-local.tls: true
        runtipi.managed: true
  wordpress_cuddleconfessions-db:
    container_name: wordpress_cuddleconfessions-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_cuddleconfessions
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_cuddleconfessions:/var/lib/wordpress_cuddleconfessions
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
