version: "3.9"
services:
      
  wordpress_sloppyhero:
    container_name: wordpress_sloppyhero
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_sloppyhero-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_sloppyhero-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-sloppyhero-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-sloppyhero.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-sloppyhero-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-sloppyhero-insecure.entrypoints: web
        traefik.http.routers.wordpress-sloppyhero-insecure.service: wordpress-sloppyhero
        traefik.http.routers.wordpress-sloppyhero-insecure.middlewares: wordpress-sloppyhero-redirect
        # Websecure
        traefik.http.routers.wordpress-sloppyhero.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-sloppyhero.entrypoints: websecure
        traefik.http.routers.wordpress-sloppyhero.service: wordpress-sloppyhero
        traefik.http.routers.wordpress-sloppyhero.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-sloppyhero-local-insecure.rule: Host(`wordpress-sloppyhero.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-sloppyhero-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-sloppyhero-local-insecure.service: wordpress-sloppyhero
        traefik.http.routers.wordpress-sloppyhero-local-insecure.middlewares: wordpress-sloppyhero-redirect
        # Local domain secure
        traefik.http.routers.wordpress-sloppyhero-local.rule: Host(`wordpress-sloppyhero.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-sloppyhero-local.entrypoints: websecure
        traefik.http.routers.wordpress-sloppyhero-local.service: wordpress-sloppyhero
        traefik.http.routers.wordpress-sloppyhero-local.tls: true
        runtipi.managed: true
  wordpress_sloppyhero-db:
    container_name: wordpress_sloppyhero-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
