version: "3.9"
services:
      
  wordpress_marleebean:
    container_name: wordpress_marleebean
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_marleebean-db
      - WORDPRESS_DB_NAME=wordpress_marleebean
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_marleebean:/var/www/wordpress_marleebean
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_marleebean-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_marleebean-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_marleebean.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_marleebean-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_marleebean-insecure.entrypoints: web
        traefik.http.routers.wordpress_marleebean-insecure.service: wordpress_marleebean
        traefik.http.routers.wordpress_marleebean-insecure.middlewares: wordpress_marleebean-redirect
        # Websecure
        traefik.http.routers.wordpress_marleebean.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_marleebean.entrypoints: websecure
        traefik.http.routers.wordpress_marleebean.service: wordpress_marleebean
        traefik.http.routers.wordpress_marleebean.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_marleebean-local-insecure.rule: Host(`wordpress_marleebean.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_marleebean-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_marleebean-local-insecure.service: wordpress_marleebean
        traefik.http.routers.wordpress_marleebean-local-insecure.middlewares: wordpress_marleebean-redirect
        # Local domain secure
        traefik.http.routers.wordpress_marleebean-local.rule: Host(`wordpress_marleebean.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_marleebean-local.entrypoints: websecure
        traefik.http.routers.wordpress_marleebean-local.service: wordpress_marleebean
        traefik.http.routers.wordpress_marleebean-local.tls: true
        runtipi.managed: true
  wordpress_marleebean-db:
    container_name: wordpress_marleebean-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_marleebean
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_marleebean:/var/lib/wordpress_marleebean
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
