version: "3.9"
services:
      
  wordpress_hometownheartstrings:
    container_name: wordpress_hometownheartstrings
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_hometownheartstrings-db
      - WORDPRESS_DB_NAME=wordpress_hometownheartstrings
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_hometownheartstrings:/var/www/wordpress_hometownheartstrings
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_hometownheartstrings-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_hometownheartstrings-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_hometownheartstrings.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_hometownheartstrings-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_hometownheartstrings-insecure.entrypoints: web
        traefik.http.routers.wordpress_hometownheartstrings-insecure.service: wordpress_hometownheartstrings
        traefik.http.routers.wordpress_hometownheartstrings-insecure.middlewares: wordpress_hometownheartstrings-redirect
        # Websecure
        traefik.http.routers.wordpress_hometownheartstrings.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_hometownheartstrings.entrypoints: websecure
        traefik.http.routers.wordpress_hometownheartstrings.service: wordpress_hometownheartstrings
        traefik.http.routers.wordpress_hometownheartstrings.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_hometownheartstrings-local-insecure.rule: Host(`wordpress_hometownheartstrings.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_hometownheartstrings-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_hometownheartstrings-local-insecure.service: wordpress_hometownheartstrings
        traefik.http.routers.wordpress_hometownheartstrings-local-insecure.middlewares: wordpress_hometownheartstrings-redirect
        # Local domain secure
        traefik.http.routers.wordpress_hometownheartstrings-local.rule: Host(`wordpress_hometownheartstrings.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_hometownheartstrings-local.entrypoints: websecure
        traefik.http.routers.wordpress_hometownheartstrings-local.service: wordpress_hometownheartstrings
        traefik.http.routers.wordpress_hometownheartstrings-local.tls: true
        runtipi.managed: true
  wordpress_hometownheartstrings-db:
    container_name: wordpress_hometownheartstrings-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_hometownheartstrings
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_hometownheartstrings:/var/lib/wordpress_hometownheartstrings
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
