version: "2.1"

services:
  grist:
    container_name: grist
    environment:
      - APP_HOME_URL=${APP_PROTOCOL:-http}://${APP_DOMAIN}
      - GRIST_SANDBOX_FLAVOR=${GRIST_SANDBOX_FLAVOR}
    image: "gristlabs/grist:1.3.2"
      - GRIST_SANDBOX_FLAVOR: gvisor
      - GRIST_FORWARD_AUTH_HEADER: X-Forwarded-User
      - GRIST_FORWARD_AUTH_LOGOUT_PATH: _oauth/logout
      - GRIST_SINGLE_ORG: rasies 
      - GRIST_SESSION_SECRET=Mycobacteri@98
      - GRIST_DEFAULT_EMAIL=ianras@yahoo.com
      - GRIST_FORWARD_AUTH_HEADER=X-Forwarded-User
      - GRIST_FORWARD_AUTH_LOGOUT_PATH=_oauth/logout
      - GRIST_SINGLE_ORG=rasies
    ports:
      - "${APP_PORT:-8484}:8484"
    restart: always
    volumes:
      - "${APP_DATA_DIR}/data/grist-data:/persist"
      - "${APP_DATA_DIR}/data/grist-data/tmp:/persist/tmp"
    networks:
      - tipi_main_network
    labels:
      # Enable Traefik
      traefik.enable: true

      # Service port
      traefik.http.services.grist.loadbalancer.server.port: 8484

      # Middleware to set HTTPS headers
      traefik.http.middlewares.grist-https-headers.headers.customrequestheaders.X-Forwarded-Proto: https

      # Web (HTTP) - Redirect HTTP to HTTPS
      traefik.http.routers.grist-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grist-insecure.entrypoints: web
      traefik.http.routers.grist-insecure.service: grist
      traefik.http.routers.grist-insecure.middlewares: grist-https-headers

      # Websecure (HTTPS)
      traefik.http.routers.grist.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.grist.entrypoints: websecure
      traefik.http.routers.grist.tls.certresolver: myresolver
      traefik.http.routers.grist.service: grist
      traefik.http.routers.grist.middlewares: grist-https-headers

      # Local domain (HTTP)
      traefik.http.routers.grist-local-insecure.rule: Host(`${LOCAL_DOMAIN}`)
      traefik.http.routers.grist-local-insecure.entrypoints: web
      traefik.http.routers.grist-local-insecure.service: grist
      traefik.http.routers.grist-local-insecure.middlewares: grist-https-headers

      # Local domain secure (HTTPS)
      traefik.http.routers.grist-local.rule: Host(`${LOCAL_DOMAIN}`)
      traefik.http.routers.grist-local.entrypoints: websecure
      traefik.http.routers.grist-local.service: grist
      traefik.http.routers.grist-local.tls: true
      traefik.http.routers.grist-local.middlewares: grist-https-headers
      runtipi.managed: true

networks:
  tipi_main_network:
    driver: bridge

