version: "3.9"
services:

  wordpress-noreleasepower:
    container_name: wordpress-noreleasepower
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress-noreleasepower-db
      - WORDPRESS_DB_NAME=wordpress-noreleasepower-db
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress-noreleasepower-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-noreleasepower-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-noreleasepower.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-noreleasepower-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-noreleasepower-insecure.entrypoints: web
        traefik.http.routers.wordpress-noreleasepower-insecure.service: wordpress-noreleasepower
        traefik.http.routers.wordpress-noreleasepower-insecure.middlewares: wordpress-noreleasepower-redirect
        # Websecure
        traefik.http.routers.wordpress-noreleasepower.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-noreleasepower.entrypoints: websecure
        traefik.http.routers.wordpress-noreleasepower.service: wordpress-noreleasepower
        traefik.http.routers.wordpress-noreleasepower.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-noreleasepower-local-insecure.rule: Host(`wordpress-noreleasepower.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-noreleasepower-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-noreleasepower-local-insecure.service: wordpress-noreleasepower
        traefik.http.routers.wordpress-noreleasepower-local-insecure.middlewares: wordpress-noreleasepower-redirect
        # Local domain secure
        traefik.http.routers.wordpress-noreleasepower-local.rule: Host(`wordpress-noreleasepower.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-noreleasepower-local.entrypoints: websecure
        traefik.http.routers.wordpress-noreleasepower-local.service: wordpress-noreleasepower
        traefik.http.routers.wordpress-noreleasepower-local.tls: true
        runtipi.managed: true
  wordpress-noreleasepower-db:
    container_name: wordpress-noreleasepower-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress-noreleasepower-db
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

