version: "3.9"

services:
  collabora:
    image: collabora/code
    container_name: collabora
    environment:
      - domain=cool\\.rasies\\.com  # Escaped dots for domain
      - enable_admin_console=true
      - username=ianras  # Removed the underscore from "admin_"
      - password=Mycobacteri@98
      - enable_macros=true
      - dictionaries=en_US
    ports:
      - "9980:9980"  # Direct port mapping for Collabora
    volumes:
      - ${APP_DATA_DIR}/data/collabora:/var/lib/lool
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Enable Traefik for this service
      traefik.enable: true
      # Redirect HTTP to HTTPS
      traefik.http.middlewares.collabora-redirect.redirectscheme.scheme: https
      # Load balancing service for Collabora
      traefik.http.services.collabora.loadbalancer.server.port: 9980
      # Insecure (HTTP) Router
      traefik.http.routers.collabora-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.collabora-insecure.entrypoints: web
      traefik.http.routers.collabora-insecure.middlewares: collabora-redirect
      # Secure (HTTPS) Router
      traefik.http.routers.collabora.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.collabora.entrypoints: websecure
      traefik.http.routers.collabora.service: collabora
      traefik.http.routers.collabora.tls.certresolver: myresolver
      # Local domain (insecure HTTP)
      traefik.http.routers.collabora-local-insecure.rule: Host(`collabora.${LOCAL_DOMAIN}`)
      traefik.http.routers.collabora-local-insecure.entrypoints: web
      traefik.http.routers.collabora-local-insecure.middlewares: collabora-redirect
      # Local domain secure
      traefik.http.routers.collabora-local.rule: Host(`collabora.${LOCAL_DOMAIN}`)
      traefik.http.routers.collabora-local.entrypoints: websecure
      traefik.http.routers.collabora-local.tls.certresolver: myresolver
      runtipi.managed: true

  collabora-db:
    container_name: collabora-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=collabora
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true

