version: "3.9"
services:

  wordpress-saturnseer:
    container_name: wordpress-saturnseer
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress-saturnseer-db
      - WORDPRESS_DB_NAME=wordpress-saturnseer-db
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress-saturnseer-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress-saturnseer-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-saturnseer.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-saturnseer-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-saturnseer-insecure.entrypoints: web
        traefik.http.routers.wordpress-saturnseer-insecure.service: wordpress-saturnseer
        traefik.http.routers.wordpress-saturnseer-insecure.middlewares: wordpress-saturnseer-redirect
        # Websecure
        traefik.http.routers.wordpress-saturnseer.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-saturnseer.entrypoints: websecure
        traefik.http.routers.wordpress-saturnseer.service: wordpress-saturnseer
        traefik.http.routers.wordpress-saturnseer.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-saturnseer-local-insecure.rule: Host(`wordpress-saturnseer.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-saturnseer-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-saturnseer-local-insecure.service: wordpress-saturnseer
        traefik.http.routers.wordpress-saturnseer-local-insecure.middlewares: wordpress-saturnseer-redirect
        # Local domain secure
        traefik.http.routers.wordpress-saturnseer-local.rule: Host(`wordpress-saturnseer.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-saturnseer-local.entrypoints: websecure
        traefik.http.routers.wordpress-saturnseer-local.service: wordpress-saturnseer
        traefik.http.routers.wordpress-saturnseer-local.tls: true
        runtipi.managed: true
  wordpress-saturnseer-db:
    container_name: wordpress-saturnseer-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress-saturnseer-db
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

