version: "3.9"

services:
  collabora:
    image: collabora/code:latest
    container_name: collabora
    environment:
      - domain=data\\.rasies\\.com  # Escape dots for the domain
      - enable_admin_console=true
      - username=ianras
      - password=Mycobacteri@98
      - dictionaries=en_US
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false  # Disable SSL within Collabora
    ports:
      - "9980:9980"
    volumes:
      - ${APP_DATA_DIR}/data/collabora:/var/lib/lool
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Enable Traefik for this service
      - traefik.enable=true
      # Redirect HTTP to HTTPS
      - traefik.http.middlewares.collabora-redirect.redirectscheme.scheme=https
      # Define HTTP router to handle insecure connections
      - traefik.http.routers.collabora-insecure.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.collabora-insecure.entrypoints=web
      - traefik.http.routers.collabora-insecure.middlewares=collabora-redirect
      # Define HTTPS router to handle secure connections
      - traefik.http.routers.collabora.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.collabora.entrypoints=websecure
      - traefik.http.routers.collabora.tls.certresolver=myresolver
      # Local domain configuration (optional)
      - traefik.http.routers.collabora-local-insecure.rule=Host(`collabora.${LOCAL_DOMAIN}`)
      - traefik.http.routers.collabora-local-insecure.entrypoints=web
      - traefik.http.routers.collabora-local-insecure.middlewares=collabora-redirect
      - traefik.http.routers.collabora-local.rule=Host(`collabora.${LOCAL_DOMAIN}`)
      - traefik.http.routers.collabora-local.entrypoints=websecure
      - traefik.http.routers.collabora-local.tls.certresolver=myresolver
      - traefik.http.services.collabora.loadbalancer.server.port=9980
      - runtipi.managed=true

  collabora-db:
    container_name: collabora-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=collabora
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      - runtipi.managed=true

networks:
  tipi_main_network:
    external: true

