version: "3.9"
services:
      
  wordpress_aweggly:
    container_name: wordpress_aweggly
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_aweggly-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_aweggly-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_aweggly-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_aweggly.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_aweggly-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_aweggly-insecure.entrypoints: web
        traefik.http.routers.wordpress_aweggly-insecure.service: wordpress_aweggly
        traefik.http.routers.wordpress_aweggly-insecure.middlewares: wordpress_aweggly-redirect
        # Websecure
        traefik.http.routers.wordpress_aweggly.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_aweggly.entrypoints: websecure
        traefik.http.routers.wordpress_aweggly.service: wordpress_aweggly
        traefik.http.routers.wordpress_aweggly.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_aweggly-local-insecure.rule: Host(`wordpress_aweggly.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_aweggly-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_aweggly-local-insecure.service: wordpress_aweggly
        traefik.http.routers.wordpress_aweggly-local-insecure.middlewares: wordpress_aweggly-redirect
        # Local domain secure
        traefik.http.routers.wordpress_aweggly-local.rule: Host(`wordpress_aweggly.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_aweggly-local.entrypoints: websecure
        traefik.http.routers.wordpress_aweggly-local.service: wordpress_aweggly
        traefik.http.routers.wordpress_aweggly-local.tls: true
        runtipi.managed: true
  wordpress_aweggly-db:
    container_name: wordpress_aweggly-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
