version: "3.9"
services:
      
  wordpress_kiracuts:
    container_name: wordpress_kiracuts
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_kiracuts-db
      - WORDPRESS_DB_NAME=wordpress_kiracuts
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_kiracuts:/var/www/wordpress_kiracuts
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_kiracuts-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_kiracuts-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_kiracuts.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_kiracuts-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_kiracuts-insecure.entrypoints: web
        traefik.http.routers.wordpress_kiracuts-insecure.service: wordpress_kiracuts
        traefik.http.routers.wordpress_kiracuts-insecure.middlewares: wordpress_kiracuts-redirect
        # Websecure
        traefik.http.routers.wordpress_kiracuts.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_kiracuts.entrypoints: websecure
        traefik.http.routers.wordpress_kiracuts.service: wordpress_kiracuts
        traefik.http.routers.wordpress_kiracuts.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_kiracuts-local-insecure.rule: Host(`wordpress_kiracuts.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_kiracuts-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_kiracuts-local-insecure.service: wordpress_kiracuts
        traefik.http.routers.wordpress_kiracuts-local-insecure.middlewares: wordpress_kiracuts-redirect
        # Local domain secure
        traefik.http.routers.wordpress_kiracuts-local.rule: Host(`wordpress_kiracuts.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_kiracuts-local.entrypoints: websecure
        traefik.http.routers.wordpress_kiracuts-local.service: wordpress_kiracuts
        traefik.http.routers.wordpress_kiracuts-local.tls: true
        runtipi.managed: true
  wordpress_kiracuts-db:
    container_name: wordpress_kiracuts-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress_kiracuts
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress_kiracuts:/var/lib/wordpress_kiracuts
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
