version: "3.9"
services:
      
<<<<<<< HEAD
  wordpress-aidanras:
    container_name: wordpress-aidanras
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress-aidanras-db
=======
  wordpress_aidanras:
    container_name: wordpress_aidanras
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_aidanras-db
>>>>>>> 4ea07c22
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
<<<<<<< HEAD
      - wordpress-aidanras-db
=======
      - wordpress_aidanras-db
>>>>>>> 4ea07c22
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
<<<<<<< HEAD
        traefik.http.middlewares.wordpress-aidanras-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress-aidanras.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress-aidanras-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-aidanras-insecure.entrypoints: web
        traefik.http.routers.wordpress-aidanras-insecure.service: wordpress-aidanras
        traefik.http.routers.wordpress-aidanras-insecure.middlewares: wordpress-aidanras-redirect
        # Websecure
        traefik.http.routers.wordpress-aidanras.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress-aidanras.entrypoints: websecure
        traefik.http.routers.wordpress-aidanras.service: wordpress-aidanras
        traefik.http.routers.wordpress-aidanras.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress-aidanras-local-insecure.rule: Host(`wordpress-aidanras.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-aidanras-local-insecure.entrypoints: web
        traefik.http.routers.wordpress-aidanras-local-insecure.service: wordpress-aidanras
        traefik.http.routers.wordpress-aidanras-local-insecure.middlewares: wordpress-aidanras-redirect
        # Local domain secure
        traefik.http.routers.wordpress-aidanras-local.rule: Host(`wordpress-aidanras.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress-aidanras-local.entrypoints: websecure
        traefik.http.routers.wordpress-aidanras-local.service: wordpress-aidanras
        traefik.http.routers.wordpress-aidanras-local.tls: true
        runtipi.managed: true
  wordpress-aidanras-db:
    container_name: wordpress-aidanras-db
=======
        traefik.http.middlewares.wordpress_aidanras-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_aidanras.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_aidanras-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras-insecure.entrypoints: web
        traefik.http.routers.wordpress_aidanras-insecure.service: wordpress_aidanras
        traefik.http.routers.wordpress_aidanras-insecure.middlewares: wordpress_aidanras-redirect
        # Websecure
        traefik.http.routers.wordpress_aidanras.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras.entrypoints: websecure
        traefik.http.routers.wordpress_aidanras.service: wordpress_aidanras
        traefik.http.routers.wordpress_aidanras.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_aidanras-local-insecure.rule: Host(`wordpress_aidanras.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_aidanras-local-insecure.service: wordpress_aidanras
        traefik.http.routers.wordpress_aidanras-local-insecure.middlewares: wordpress_aidanras-redirect
        # Local domain secure
        traefik.http.routers.wordpress_aidanras-local.rule: Host(`wordpress_aidanras.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_aidanras-local.entrypoints: websecure
        traefik.http.routers.wordpress_aidanras-local.service: wordpress_aidanras
        traefik.http.routers.wordpress_aidanras-local.tls: true
        runtipi.managed: true
  wordpress_aidanras-db:
    container_name: wordpress_aidanras-db
>>>>>>> 4ea07c22
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
