version: "3.9"
services:
      
  wordpress_usmender:
    container_name: wordpress_usmender
    image: wordpress:6.6.1
    environment:
      - WORDPRESS_DB_HOST=wordpress_usmender-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=tipi
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/wordpress:/var/www/html
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    depends_on:
      - wordpress_usmender-db
    networks:
      - tipi_main_network
    labels:
        # Main
        traefik.enable: true
        traefik.http.middlewares.wordpress_usmender-redirect.redirectscheme.scheme: https
        traefik.http.services.wordpress_usmender.loadbalancer.server.port: 80
        # Web
        traefik.http.routers.wordpress_usmender-insecure.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_usmender-insecure.entrypoints: web
        traefik.http.routers.wordpress_usmender-insecure.service: wordpress_usmender
        traefik.http.routers.wordpress_usmender-insecure.middlewares: wordpress_usmender-redirect
        # Websecure
        traefik.http.routers.wordpress_usmender.rule: Host(`${APP_DOMAIN}`)
        traefik.http.routers.wordpress_usmender.entrypoints: websecure
        traefik.http.routers.wordpress_usmender.service: wordpress_usmender
        traefik.http.routers.wordpress_usmender.tls.certresolver: myresolver
        # Local domain
        traefik.http.routers.wordpress_usmender-local-insecure.rule: Host(`wordpress_usmender.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_usmender-local-insecure.entrypoints: web
        traefik.http.routers.wordpress_usmender-local-insecure.service: wordpress_usmender
        traefik.http.routers.wordpress_usmender-local-insecure.middlewares: wordpress_usmender-redirect
        # Local domain secure
        traefik.http.routers.wordpress_usmender-local.rule: Host(`wordpress_usmender.${LOCAL_DOMAIN}`)
        traefik.http.routers.wordpress_usmender-local.entrypoints: websecure
        traefik.http.routers.wordpress_usmender-local.service: wordpress_usmender
        traefik.http.routers.wordpress_usmender-local.tls: true
        runtipi.managed: true
  wordpress_usmender-db:
    container_name: wordpress_usmender-db
    image: mariadb:11.1.3
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=tipi
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true
