export default function HomePage() {
  return (
    <main className="grid gap-6">
      <section className="arcade-panel p-8">
        <p className="font-arcade text-xs text-arcade-pink">Retro Arcade</p>
        <h2 className="mt-4 text-4xl font-semibold">Jogmania Arena</h2>
        <p className="mt-4 text-lg text-white/80">
          Welcome to Jogmania, a running quest platform with AI-powered narration and
          shareable run exports. This shell is wired for iOS, Web, and API with shared
          types.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <a className="arcade-button" href="/run">
            Start a Run
          </a>
          <a className="rounded-lg border border-white/20 px-4 py-2" href="/quest">
            Get a Quest
          </a>
        </div>
      </section>

      <section className="grid gap-4 md:grid-cols-3">
        {[
          {
            title: "Quest Engine",
            body: "Daily quests generated by an OpenAI-compatible endpoint with offline fallbacks."
          },
          {
            title: "Run Telemetry",
            body: "Create and list runs. Store stats in Postgres and export to MinIO."
          },
          {
            title: "Shared Types",
            body: "OpenAPI generates a typed client for both Next.js and Expo."
          }
        ].map((item) => (
          <div key={item.title} className="arcade-panel p-6">
            <h3 className="text-xl font-semibold">{item.title}</h3>
            <p className="mt-3 text-white/75">{item.body}</p>
          </div>
        ))}
      </section>
    </main>
  );
}
