version: "3.9"

services:
  api:
    image: localai/localai:v2.20.1-sycl-f32-ffmpeg
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8111/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8111:8111
    environment:
      - DEBUG=true
      # ...
    volumes:
      - ./models:/build/models:cached
      - ${ROOT_FOLDER_HOST}/media/data/images/:/tmp/generated/images/ 
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.localai-redirect.redirectscheme.scheme: https
      traefik.http.services.localai.loadbalancer.server.port: 8111
      # Web
      traefik.http.routers.localai-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.localai-insecure.entrypoints: web
      traefik.http.routers.localai-insecure.service: localai
      traefik.http.routers.localai-insecure.middlewares: localai-web-redirect
      # Websecure
      traefik.http.routers.localai.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.localai.entrypoints: websecure
      traefik.http.routers.localai.service: localai
      traefik.http.routers.localai.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.localai-local-insecure.rule: Host(`localai.${LOCAL_DOMAIN}`)
      traefik.http.routers.localai-local-insecure.entrypoints: web
      traefik.http.routers.localai-local-insecure.service: localai
      traefik.http.routers.localai-local-insecure.middlewares: localai-web-redirect
      # Local domain secure
      traefik.http.routers.localai-local.rule: Host(`localai.${LOCAL_DOMAIN}`)
      traefik.http.routers.localai-local.entrypoints: websecure
      traefik.http.routers.localai-local.service: localai
      traefik.http.routers.localai-local.tls: true 
      runtipi.managed: true

networks:
  tipi_main_network:
    driver: overlay
